services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: paperly_app
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    environment:
      - GO111MODULE=on
    networks:
      - paperly-network
volumes:
  air_config:
