services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: paperly_app
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
      - air_config:/root/.air.toml
    environment:
      - GO111MODULE=on
      - AIR_WATCH_DELAY=1000ms
      - AIR_TMP_DIR=/app/tmp

volumes:
  air_config:
